### ISSUE TITLE
Detected invalid array contents due to unsynchronized modifications with concurrent users>

### ISSUE THREAD

**Issue by tom916** [logstash-plugins/logstash-codec-compress_spooler#8]
```
input {
  file {
    type => "nginx_error"
    start_position => "beginning"
    path => [ "/data1/logs/nginx/error.log"]
  }
}

output {

    rabbitmq {
        exchange => "amp.fanout"
        exchange_type => "fanout"
        host => "127.0.0.1"
        port => "5676"
        codec => compress_spooler {}
        workers => 8
    }
}
```

When workers num big than 1,fllow The following error appears

```
Error encoding event {:exception=>#<ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users>, :event=>#<LogStash::Event:0x4270af83 @metadata_accessors=#<LogStash::Util::Accessors:0x47c9e96f @store={"path"=>"/data1/logs/nginx/error.log"}, @lut={"[path]"=>[{"path"=>"/data1/logs/nginx/error.log"}, "path"]}>, @cancelled=false, @data={"message"=>"2015/06/27 10:45:54 [debug] 5583#0: accept mutex lock failed: 0", "@version"=>"1", "@timestamp"=>"2015-10-13T01:49:07.495Z", "host"=>"dev2.aifang.com", "path"=>"/data1/logs/nginx/error.log", "type"=>"nginx_error"}, @metadata={"path"=>"/data1/logs/nginx/error.log"}, @accessors=#<LogStash::Util::Accessors:0x632fd8cb @store={"message"=>"2015/06/27 10:45:54 [debug] 5583#0: accept mutex lock failed: 0", "@version"=>"1", "@timestamp"=>"2015-10-13T01:49:07.495Z", "host"=>"dev2.aifang.com", "path"=>"/data1/logs/nginx/error.log", "type"=>"nginx_error"}, @lut={"host"=>[{"message"=>"2015/06/27 10:45:54 [debug] 5583#0: accept mutex lock failed: 0", "@version"=>"1", "@timestamp"=>"2015-10-13T01:49:07.495Z", "host"=>"dev2.aifang.com", "path"=>"/data1/logs/nginx/error.log", "type"=>"nginx_error"}, "host"], "path"=>[{"message"=>"2015/06/27 10:45:54 [debug] 5583#0: accept mutex lock failed: 0", "@version"=>"1", "@timestamp"=>"2015-10-13T01:49:07.495Z", "host"=>"dev2.aifang.com", "path"=>"/data1/logs/nginx/error.log", "type"=>"nginx_error"}, "path"], "type"=>[{"message"=>"2015/06/27 10:45:54 [debug] 5583#0: accept mutex lock failed: 0", "@version"=>"1", "@timestamp"=>"2015-10-13T01:49:07.495Z", "host"=>"dev2.aifang.com", "path"=>"/data1/logs/nginx/error.log", "type"=>"nginx_error"}, "type"]}>>, :level=>:warn}
org/msgpack/jruby/MessagePackLibrary.java:62:in `pack'
logstash-1.5.4/vendor/local_gems/81ca8cfc/logstash-codec-compress_spooler-0.2.1/lib/logstash/codecs/compress_spooler.rb:44:in `compress'
logstash-1.5.4/vendor/local_gems/81ca8cfc/logstash-codec-compress_spooler-0.2.1/lib/logstash/codecs/compress_spooler.rb:29:in `encode'
logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-1.1.1-java/lib/logstash/outputs/rabbitmq.rb:84:in `receive'
logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88:in `handle'
logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:79:in `worker_setup'
```

**Comment by madhurkgp** [comment]
I'm facing the same issue, did you got any solution or workaround for this problem ? 

any lead would help.
